Dev
YoussefWaelMohamedLotfy/BookingClone pull request #24
Opened 2023-04-03 21:58 UTC by Salsa-beel

2023-04-04 11:43 UTC, YoussefWaelMohamedLotfy requested changes
@Salsa-beel You have forgot to add the *Paginated* Endpoints to your Controllers. Kindly add them to proceed with the merge.

2023-04-04 18:53 UTC, Salsa-beel commented
pagination part is done.
mappings are added too.

2023-04-04 19:05 UTC, YoussefWaelMohamedLotfy commented
> pagination part is done. mappings are added too.

@Salsa-beel Nothing has been pushed

2023-04-04 19:08 UTC, Salsa-beel commented
Can you check again now ?

2023-04-04 19:13 UTC, YoussefWaelMohamedLotfy commented
![image](https://user-images.githubusercontent.com/40206862/229896216-816cea1b-ed44-4fc9-bc68-cd5fd5c931ed.png)
@Salsa-beel Still nothing. When you find a commit tag like this in this PR discussion, it means it is available to public

2023-04-04 19:25 UTC, Salsa-beel commented
<img width="1204" alt="Screenshot 2023-04-04 at 9 16 07 PM" src="https://user-images.githubusercontent.com/123001325/229898753-079d4e62-f75b-4bde-97c0-499a5eb40676.png">

but I have committed and pushed all the changes and here is the history of the branch

2023-04-04 19:34 UTC, YoussefWaelMohamedLotfy commented
@Salsa-beel It turns out that you are pushing to a different Branch, named `Book-13-Implement-Hotel-Reviews` while this PR is for `dev` 😐

2023-04-04 19:53 UTC, YoussefWaelMohamedLotfy requested changes
Please complete the mentioned

2023-04-04 19:53 UTC, YoussefWaelMohamedLotfy commented on src/Services/BookingClone.API/Controllers/V1/AttractionReviewsController.cs
Missing Endpoints for pagination

2023-04-04 19:53 UTC, YoussefWaelMohamedLotfy commented on src/Services/BookingClone.API/Controllers/V1/HotelReviewsController.cs
Missing Endpoints for pagination

2023-04-04 19:53 UTC, YoussefWaelMohamedLotfy commented on src/Services/BookingClone.Application/Features/AttractionReviewFeatures/EntityMappingConfig.cs
What about the actual Mapping? 🤣

2023-04-04 19:53 UTC, YoussefWaelMohamedLotfy commented on src/Services/BookingClone.Application/Features/HotelReviewFeatures/EntityMappingConfig.cs
What about the actual Mapping? 🤣

2023-04-04 20:04 UTC, Salsa-beel commented
@YoussefWaelMohamedLotfy 

<img width="1204" alt="Screenshot 2023-04-04 at 9 16 07 PM" src="https://user-images.githubusercontent.com/123001325/229907180-989bc02a-9854-4930-b33f-83b471c0be5a.png">

aren't these the pagination part and entity map config file ? or you meant something else ?

2023-04-04 20:09 UTC, YoussefWaelMohamedLotfy commented
> aren't these the pagination part and entity map config file ? or you meant something else ?

@Salsa-beel Your Query Handlers are done, but throw exceptions when trying to invoke them because of not configuring mapping. You added files for configuring the mappings but did not add the maps 😞 Also, you should an endpoint for Pagination in the controllers. Kindly finish and test then ask for a review again when done.

2023-04-04 20:15 UTC, YoussefWaelMohamedLotfy commented on src/WebApps/BookingClone.Admin/EntityMappingConfig.cs
Correct Configs, but wrong place 👀

2023-04-04 21:36 UTC, Salsa-beel commented on src/WebApps/BookingClone.Admin/EntityMappingConfig.cs
did all the changes needed, added the maps in the entity map config and made sure the file is in the correct place, deleted the wrong one, also added the pagination code needed in the hotel review & attraction review controller, all these changes are done on the dev branch, hopefully this time it works out, let me know if anything else needs to be edited.

2023-04-04 21:54 UTC, YoussefWaelMohamedLotfy commented on src/Services/BookingClone.Application/Features/AttractionReviewFeatures/Queries/GetAllAttractionReviews/GetAllAttractionReviewsQueryHandler.cs
@Salsa-beel Missing Logic here

2023-04-04 23:26 UTC, Salsa-beel commented on src/Services/BookingClone.Application/Features/AttractionReviewFeatures/Queries/GetAllAttractionReviews/GetAllAttractionReviewsQueryHandler.cs
done

2023-04-05 08:20 UTC, YoussefWaelMohamedLotfy approved these changes

2023-04-05 08:20 UTC, merged